### ISSUE TITLE
能否支持 Clast-Meta 这个fork

### ISSUE THREAD

**Issue by bash99** [Kr328/without-clash#1]
试了试，很好用，总算可以正常测ping了。

但是用 [ClashMeta](https://github.com/MetaCubeX/Clash.Meta/) 这个fork时失效了。

有个区别是Clash-Premium的tun配置我写的
  stack: system
而 Clash-Meta的tun配置用的
  stack: gvisor #  only gvisor

**Comment by Kr328** [comment]
不能 本项目开源 请自行修改

**Comment by bash99** [comment]
主要是看不懂代码的原理，看了半天总之是cgroup + route，于是放狗搜，不过最后还是按 "linux bypass tun device" 找到了原理
原理在此 
https://superuser.com/questions/271915/route-the-traffic-over-specific-interface-for-a-process-in-linux/1048913#1048913
脚本在
https://gist.github.com/kriswebdev/a8d291936fe4299fb17d3744497b1170
兼容(cgroup1/2)

靠这个novpn.sh能正常跳过tune，只是novpn.sh需要手动设置原始网口。

供其它人参考。

仍然感谢Kr328这个项目给我带来了方向。
